services:
  document_slicer:
    build: ./services/document_slicer
    container_name: document_slicer
    ports:
      - "8090:8000"
    restart: unless-stopped

  ai_legal:
    build: ./services/ai_legal
    container_name: ai_legal
    environment:
      - OLLAMA_BASE_URL=http://192.168.3.63:11434
      - OLLAMA_MODEL=qwen3:14b
    ports:
      - "8092:8000"
    restart: unless-stopped

  admin-panel:
    build:
      context: ./services/admin-panel
      args:
        VITE_SLICER_API_BASE_URL: http://localhost:8090
        VITE_AI_LAWYER_API_BASE_URL: http://localhost:8092
    container_name: admin-panel
    environment:
      - VITE_SLICER_API_BASE_URL=http://localhost:8090
      - VITE_AI_LAWYER_API_BASE_URL=http://localhost:8092
    ports:
      - "8091:80"
    restart: unless-stopped